### PR TITLE
CMake build support

### PR DESCRIPTION
**Pull request by msoucy**
Changes makefiles in favor of cmake, to allow (eventual) Windows builds, better cross-platform support, and more maintainable/fast/pretty builds

### CODE REVIEW

**Comment by msoucy** [comment]
I blame Travis for having out-of-date everythings.

**Comment by liam-middlebrook** [comment]
Is there a way we can still have the binaries placed into the bin folder instead of the root directory?

**Comment by msoucy** [comment]
Use an out of source build

**Comment by msoucy** [comment]
IT'S ALIVE!

**Comment by liam-middlebrook** [comment]
LGTM :+1:

**Pull request merged**
